// <auto-generated />
namespace Educon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Novas_Modificacoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Novas_Modificacoes));
        
        string IMigrationMetadata.Id
        {
            get { return "201709301828558_Novas_Modificacoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
